pages = [{"l":"index.html#","e":false,"i":"","n":"folio","t":"folio","d":"","k":"static","x":""},
{"l":"folio.html#","e":false,"i":"","n":"folio","t":"folio","d":"","k":"package","x":""},
{"l":"folio.html#Cursor-0","e":false,"i":"","n":"Cursor","t":"Cursor","d":"folio","k":"type","x":""},
{"l":"folio.html#Limit-0","e":false,"i":"","n":"Limit","t":"Limit","d":"folio","k":"type","x":""},
{"l":"folio.html#ascending-6ac","e":false,"i":"extension [FIELD](field: FIELD)","n":"ascending","t":"ascending: SortBy[FIELD]","d":"folio","k":"def","x":""},
{"l":"folio.html#decode-fffffd4d","e":false,"i":"extension (cursor: Cursor)","n":"decode","t":"decode[FIELD : FieldSchema](query: Query[FIELD])(implicit evidence$1: FieldSchema[FIELD], CursorCodec): Either[CursorDecodingError, DecodedCursor]","d":"folio","k":"def","x":""},
{"l":"folio.html#descending-6ac","e":false,"i":"extension [FIELD](field: FIELD)","n":"descending","t":"descending: SortBy[FIELD]","d":"folio","k":"def","x":""},
{"l":"folio.html#encode-963","e":false,"i":"extension (decoded: DecodedCursor)","n":"encode","t":"encode[FIELD : FieldSchema](query: Query[FIELD])(implicit evidence$1: FieldSchema[FIELD], CursorCodec): Cursor","d":"folio","k":"def","x":""},
{"l":"folio.html#flipOrder-fffffac5","e":false,"i":"extension [FIELD](sortBys: ListSet[SortBy[FIELD]])","n":"flipOrder","t":"flipOrder: ListSet[SortBy[FIELD]]","d":"folio","k":"def","x":""},
{"l":"folio.html#name-8f7","e":false,"i":"extension [FIELD](field: FIELD)(using fieldSchema: FieldSchema[FIELD])","n":"name","t":"name: String","d":"folio","k":"def","x":""},
{"l":"folio.html#toCursor-812","e":false,"i":"extension [FIELD](query: Query[FIELD])(implicit evidence$1: FieldSchema[FIELD], CursorCodec)","n":"toCursor","t":"toCursor(direction: Direction = ...): Cursor","d":"folio","k":"def","x":""},
{"l":"folio/Cursor$.html#","e":false,"i":"","n":"Cursor","t":"Cursor","d":"folio","k":"object","x":""},
{"l":"folio/Cursor$.html#apply-fffff2ca","e":false,"i":"","n":"apply","t":"apply(value: String): Cursor","d":"folio.Cursor","k":"def","x":""},
{"l":"folio/Cursor$.html#decode-fffffdf7","e":false,"i":"","n":"decode","t":"decode[FIELD : FieldSchema](cursor: Cursor, query: Query[FIELD])(implicit evidence$1: FieldSchema[FIELD], codec: CursorCodec): Either[CursorDecodingError, DecodedCursor]","d":"folio.Cursor","k":"def","x":""},
{"l":"folio/Cursor$.html#encode-3b7","e":false,"i":"","n":"encode","t":"encode[FIELD : FieldSchema](decoded: DecodedCursor, query: Query[FIELD])(implicit evidence$1: FieldSchema[FIELD], codec: CursorCodec): Cursor","d":"folio.Cursor","k":"def","x":""},
{"l":"folio/Cursor$.html#value-fffff2ca","e":false,"i":"extension (cursor: Cursor)","n":"value","t":"value: String","d":"folio.Cursor","k":"def","x":""},
{"l":"folio/CursorCodec.html#","e":false,"i":"","n":"CursorCodec","t":"CursorCodec","d":"folio","k":"trait","x":""},
{"l":"folio/CursorCodec.html#decode-fffffbe4","e":false,"i":"","n":"decode","t":"decode(cursor: Cursor): Either[CursorDecodingError, String]","d":"folio.CursorCodec","k":"def","x":""},
{"l":"folio/CursorCodec.html#encode-fffff2ca","e":false,"i":"","n":"encode","t":"encode(raw: String): String","d":"folio.CursorCodec","k":"def","x":""},
{"l":"folio/CursorCodec$.html#","e":false,"i":"","n":"CursorCodec","t":"CursorCodec","d":"folio","k":"object","x":""},
{"l":"folio/CursorCodec$.html#given_CursorCodec-0","e":false,"i":"","n":"given_CursorCodec","t":"given_CursorCodec: given_CursorCodec","d":"folio.CursorCodec","k":"given","x":""},
{"l":"folio/CursorCodec$$given_CursorCodec$.html#","e":false,"i":"","n":"given_CursorCodec","t":"given_CursorCodec extends CursorCodec","d":"folio.CursorCodec","k":"object","x":""},
{"l":"folio/CursorCodec$$given_CursorCodec$.html#decode-fffffbe4","e":false,"i":"","n":"decode","t":"decode(cursor: Cursor): Either[CursorDecodingError, String]","d":"folio.CursorCodec.given_CursorCodec","k":"def","x":""},
{"l":"folio/CursorCodec$$given_CursorCodec$.html#encode-fffff2ca","e":false,"i":"","n":"encode","t":"encode(raw: String): String","d":"folio.CursorCodec.given_CursorCodec","k":"def","x":""},
{"l":"folio/DecodedCursor.html#","e":false,"i":"","n":"DecodedCursor","t":"DecodedCursor(direction: Direction, position: Position)","d":"folio","k":"class","x":""},
{"l":"folio/DecodedCursor.html#isFirst-0","e":false,"i":"","n":"isFirst","t":"isFirst: Boolean","d":"folio.DecodedCursor","k":"def","x":""},
{"l":"folio/Direction.html#","e":false,"i":"","n":"Direction","t":"Direction","d":"folio","k":"enum","x":""},
{"l":"folio/Direction.html#Forward-0","e":false,"i":"","n":"Forward","t":"Forward extends Direction","d":"folio.Direction","k":"val","x":""},
{"l":"folio/Direction.html#Backward-0","e":false,"i":"","n":"Backward","t":"Backward extends Direction","d":"folio.Direction","k":"val","x":""},
{"l":"folio/FieldSchema.html#","e":false,"i":"","n":"FieldSchema","t":"FieldSchema[FIELD]","d":"folio","k":"trait","x":""},
{"l":"folio/FieldSchema.html#fromName-fffffbe4","e":false,"i":"","n":"fromName","t":"fromName(name: String): Either[String, FIELD]","d":"folio.FieldSchema","k":"def","x":""},
{"l":"folio/FieldSchema.html#name-9f8","e":false,"i":"","n":"name","t":"name(field: FIELD): String","d":"folio.FieldSchema","k":"def","x":""},
{"l":"folio/FieldSchema$.html#","e":false,"i":"","n":"FieldSchema","t":"FieldSchema","d":"folio","k":"object","x":""},
{"l":"folio/FieldSchema$.html#fromMapping-fffffdd6","e":false,"i":"","n":"fromMapping","t":"fromMapping[FIELD](toName: FIELD => String)(using m: SumOf[FIELD]): FieldSchema[FIELD]","d":"folio.FieldSchema","k":"def","x":""},
{"l":"folio/FieldSchema$$Schema.html#","e":false,"i":"","n":"Schema","t":"Schema[FIELD](fieldsToNames: Map[FIELD, String], namesToFields: Map[String, FIELD]) extends FieldSchema[FIELD]","d":"folio.FieldSchema","k":"class","x":""},
{"l":"folio/FieldSchema$$Schema.html#fromName-fffffbe4","e":false,"i":"","n":"fromName","t":"fromName(input: String): Either[String, FIELD]","d":"folio.FieldSchema.Schema","k":"def","x":""},
{"l":"folio/FieldSchema$$Schema.html#name-9f8","e":false,"i":"","n":"name","t":"name(field: FIELD): String","d":"folio.FieldSchema.Schema","k":"def","x":""},
{"l":"folio/FieldSchema$$SnakeCase.html#","e":false,"i":"","n":"SnakeCase","t":"SnakeCase[FIELD](fieldsToNames: Map[FIELD, String], namesToFields: Map[String, FIELD]) extends Schema[FIELD]","d":"folio.FieldSchema","k":"class","x":""},
{"l":"folio/FieldSchema$$SnakeCase$.html#","e":false,"i":"","n":"SnakeCase","t":"SnakeCase","d":"folio.FieldSchema","k":"object","x":""},
{"l":"folio/FieldSchema$$SnakeCase$.html#derived-4c1","e":false,"i":"","n":"derived","t":"derived[FIELD](using m: SumOf[FIELD]): SnakeCase[FIELD]","d":"folio.FieldSchema.SnakeCase","k":"def","x":""},
{"l":"folio/FilterBy.html#","e":false,"i":"","n":"FilterBy","t":"FilterBy[FIELD]","d":"folio","k":"trait","x":""},
{"l":"folio/FilterBy.html#field-0","e":false,"i":"","n":"field","t":"field: FIELD","d":"folio.FilterBy","k":"def","x":""},
{"l":"folio/FilterBy.html#value-0","e":false,"i":"","n":"value","t":"value: String","d":"folio.FilterBy","k":"def","x":""},
{"l":"folio/FilterBy$.html#","e":false,"i":"","n":"FilterBy","t":"FilterBy","d":"folio","k":"object","x":""},
{"l":"folio/FilterBy$$ExactMatch.html#","e":false,"i":"","n":"ExactMatch","t":"ExactMatch[FIELD](field: FIELD, value: String)(implicit evidence$1: FieldSchema[FIELD]) extends FilterBy[FIELD]","d":"folio.FilterBy","k":"class","x":""},
{"l":"folio/FolioError.html#","e":false,"i":"","n":"FolioError","t":"FolioError(message: String) extends Exception","d":"folio","k":"class","x":""},
{"l":"folio/FolioError$.html#","e":false,"i":"","n":"FolioError","t":"FolioError","d":"folio","k":"object","x":""},
{"l":"folio/FolioError$$CursorDecodingError.html#","e":false,"i":"","n":"CursorDecodingError","t":"CursorDecodingError(message: String) extends FolioError","d":"folio.FolioError","k":"class","x":""},
{"l":"folio/FolioError$$CursorDecodingError$.html#","e":false,"i":"","n":"CursorDecodingError","t":"CursorDecodingError","d":"folio.FolioError","k":"object","x":""},
{"l":"folio/FolioError$$CursorDecodingError$$InvalidBase64.html#","e":false,"i":"","n":"InvalidBase64","t":"InvalidBase64(input: String) extends CursorDecodingError","d":"folio.FolioError.CursorDecodingError","k":"class","x":""},
{"l":"folio/FolioError$$CursorDecodingError$$InvalidFormat.html#","e":false,"i":"","n":"InvalidFormat","t":"InvalidFormat(expectedParts: Int, actualParts: Int) extends CursorDecodingError","d":"folio.FolioError.CursorDecodingError","k":"class","x":""},
{"l":"folio/FolioError$$CursorDecodingError$$MalformedOffset.html#","e":false,"i":"","n":"MalformedOffset","t":"MalformedOffset(offset: String) extends CursorDecodingError","d":"folio.FolioError.CursorDecodingError","k":"class","x":""},
{"l":"folio/FolioError$$CursorDecodingError$$StaleCursor$.html#","e":false,"i":"","n":"StaleCursor","t":"StaleCursor extends CursorDecodingError","d":"folio.FolioError.CursorDecodingError","k":"object","x":""},
{"l":"folio/FolioError$$CursorDecodingError$$UnknownCursorType.html#","e":false,"i":"","n":"UnknownCursorType","t":"UnknownCursorType(cursorType: String) extends CursorDecodingError","d":"folio.FolioError.CursorDecodingError","k":"class","x":""},
{"l":"folio/FolioError$$CursorDecodingError$$UnknownDirection.html#","e":false,"i":"","n":"UnknownDirection","t":"UnknownDirection(direction: String) extends CursorDecodingError","d":"folio.FolioError.CursorDecodingError","k":"class","x":""},
{"l":"folio/KeysetField.html#","e":false,"i":"","n":"KeysetField","t":"KeysetField[FIELD, T]","d":"folio","k":"trait","x":""},
{"l":"folio/KeysetField.html#field-0","e":false,"i":"","n":"field","t":"field: FIELD","d":"folio.KeysetField","k":"def","x":""},
{"l":"folio/KeysetField.html#rowId-fffff417","e":false,"i":"","n":"rowId","t":"rowId(row: T): Long","d":"folio.KeysetField","k":"def","x":""},
{"l":"folio/KeysetField$.html#","e":false,"i":"","n":"KeysetField","t":"KeysetField","d":"folio","k":"object","x":""},
{"l":"folio/KeysetField$.html#apply-106","e":false,"i":"","n":"apply","t":"apply[FIELD, T](idField: FIELD, extract: T => Long): KeysetField[FIELD, T]","d":"folio.KeysetField","k":"def","x":""},
{"l":"folio/Limit$.html#","e":false,"i":"","n":"Limit","t":"Limit","d":"folio","k":"object","x":""},
{"l":"folio/Limit$.html#Default-0","e":false,"i":"","n":"Default","t":"Default: Limit","d":"folio.Limit","k":"val","x":""},
{"l":"folio/Limit$.html#apply-fffffbe0","e":false,"i":"","n":"apply","t":"apply(n: Int): Limit","d":"folio.Limit","k":"def","x":""},
{"l":"folio/Limit$.html#value-fffffbe0","e":false,"i":"extension (limit: Limit)","n":"value","t":"value: Int","d":"folio.Limit","k":"def","x":""},
{"l":"folio/Order.html#","e":false,"i":"","n":"Order","t":"Order","d":"folio","k":"enum","x":""},
{"l":"folio/Order.html#Ascending-0","e":false,"i":"","n":"Ascending","t":"Ascending extends Order","d":"folio.Order","k":"val","x":""},
{"l":"folio/Order.html#Descending-0","e":false,"i":"","n":"Descending","t":"Descending extends Order","d":"folio.Order","k":"val","x":""},
{"l":"folio/Order$.html#","e":false,"i":"","n":"Order","t":"Order","d":"folio","k":"object","x":""},
{"l":"folio/Order$.html#Default-0","e":false,"i":"","n":"Default","t":"Default: Order","d":"folio.Order","k":"val","x":""},
{"l":"folio/Page.html#","e":false,"i":"","n":"Page","t":"Page[T](limit: Limit, previousCursor: Option[Cursor], nextCursor: Option[Cursor], data: Seq[T])","d":"folio","k":"class","x":""},
{"l":"folio/Page$.html#","e":false,"i":"","n":"Page","t":"Page","d":"folio","k":"object","x":""},
{"l":"folio/Page$.html#empty-fffffeea","e":false,"i":"","n":"empty","t":"empty[T](limit: Limit): Page[T]","d":"folio.Page","k":"def","x":""},
{"l":"folio/Page$.html#withPagination-fffff168","e":false,"i":"","n":"withPagination","t":"withPagination[F[_] : Applicative, T, FIELD : FieldSchema](query: Query[FIELD], fetchRows: (ResolvedQuery[FIELD]) => F[Seq[T]])(implicit evidence$1: Applicative[F], evidence$2: FieldSchema[FIELD], CursorCodec): F[Either[CursorDecodingError, Page[T]]]","d":"folio.Page","k":"def","x":""},
{"l":"folio/Position.html#","e":false,"i":"","n":"Position","t":"Position","d":"folio","k":"trait","x":""},
{"l":"folio/Position$.html#","e":false,"i":"","n":"Position","t":"Position","d":"folio","k":"object","x":""},
{"l":"folio/Position$.html#fromQuery-eb2","e":false,"i":"","n":"fromQuery","t":"fromQuery[FIELD : FieldSchema](query: Query[FIELD]): Position","d":"folio.Position","k":"def","x":""},
{"l":"folio/Position$$Keyset.html#","e":false,"i":"","n":"Keyset","t":"Keyset(lastId: Option[Long]) extends Position","d":"folio.Position","k":"class","x":""},
{"l":"folio/Position$$Keyset$.html#","e":false,"i":"","n":"Keyset","t":"Keyset","d":"folio.Position","k":"object","x":""},
{"l":"folio/Position$$Keyset$.html#First-0","e":false,"i":"","n":"First","t":"First: Keyset","d":"folio.Position.Keyset","k":"val","x":""},
{"l":"folio/Position$$Offset.html#","e":false,"i":"","n":"Offset","t":"Offset(offset: Long) extends Position","d":"folio.Position","k":"class","x":""},
{"l":"folio/Position$$Offset.html#next-812","e":false,"i":"","n":"next","t":"next(limit: Limit): Offset","d":"folio.Position.Offset","k":"def","x":""},
{"l":"folio/Position$$Offset.html#previous-812","e":false,"i":"","n":"previous","t":"previous(limit: Limit): Offset","d":"folio.Position.Offset","k":"def","x":""},
{"l":"folio/Position$$Offset$.html#","e":false,"i":"","n":"Offset","t":"Offset","d":"folio.Position","k":"object","x":""},
{"l":"folio/Position$$Offset$.html#First-0","e":false,"i":"","n":"First","t":"First: Offset","d":"folio.Position.Offset","k":"val","x":""},
{"l":"folio/Query.html#","e":false,"i":"","n":"Query","t":"Query[FIELD](filters: Set[FilterBy[FIELD]], sortBys: ListSet[SortBy[FIELD]], limit: Option[Limit], cursor: Option[Cursor] = ...)","d":"folio","k":"class","x":""},
{"l":"folio/Query$.html#","e":false,"i":"","n":"Query","t":"Query","d":"folio","k":"object","x":""},
{"l":"folio/Query$.html#empty-ed2","e":false,"i":"","n":"empty","t":"empty[FIELD]: Query[FIELD]","d":"folio.Query","k":"def","x":""},
{"l":"folio/ResolvedQuery.html#","e":false,"i":"","n":"ResolvedQuery","t":"ResolvedQuery[FIELD](filters: Set[FilterBy[FIELD]], sortBys: ListSet[SortBy[FIELD]], limit: Limit, position: Position)","d":"folio","k":"class","x":""},
{"l":"folio/SortBy.html#","e":false,"i":"","n":"SortBy","t":"SortBy[FIELD](order: Order, field: FIELD)(implicit evidence$1: FieldSchema[FIELD])","d":"folio","k":"class","x":""},
{"l":"docs/index.html#","e":false,"i":"","n":"folio","t":"folio","d":"","k":"static","x":""},
{"l":"docs/index.html#","e":false,"i":"","n":"Overview","t":"Overview","d":"","k":"static","x":""},
{"l":"docs/quick-example.html#","e":false,"i":"","n":"Quick Example","t":"Quick Example","d":"","k":"static","x":""},
{"l":"docs/installation.html#","e":false,"i":"","n":"Installation","t":"Installation","d":"","k":"static","x":""}];